src/models/usuario.py
import os
from src.utils.db import db
from flask_login import UserMixin
from itsdangerous import URLSafeTimedSerializer as Serializer

# UserMixin provides certain attributes and methods User model expects:
# isAuthenticated, isActive, isAnonymous, get_id()

class Usuario(db.Model, UserMixin):
    __tablename__ = "usuarios"

    id = db.Column(db.Integer, primary_key=True)
    usuario = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(100), nullable=False)
    tipo = db.Column(db.String(20), nullable=False)
    email = db.Column(db.String(100)) #, unique=True)
    telefono = db.Column(db.String(50))
    nombres = db.Column(db.String(50))
    apellidos = db.Column(db.String(50))

    departamento_id = db.Column(db.Integer, db.ForeignKey('departamentos.id')) #, nullable=False)

    # 

    def get_reset_token(self):
        s = Serializer(os.getenv('SECRET_KEY', 'clave_por_defecto'))
        return s.dumps({'user_id': self.id})#.decode('utf-8')

    @staticmethod
    def verify_reset_token(token):
        s = Serializer(os.getenv('SECRET_KEY', 'clave_por_defecto'))
        try:
            user_id = s.loads(token, max_age=1800)['user_id']
        except:
            return None
        return Usuario.query.get(user_id)
    
    def __repr__(self):
        return f"Usuario('{self.usuario}')"

src/routes/departamentos.py
from flask import Blueprint, flash, render_template, request, redirect, url_for, abort
from flask_login import current_user, login_required
from src.models.departamento import Departamento
from src.models.reporte import Reporte
from src.forms.departamentos import CrearDepartamento
from src.utils.departamentos import AREAS_TIPOS
from src import db
from sqlalchemy.sql import func

departamentos = Blueprint(
    "departamentos", __name__, url_prefix="/departamentos", template_folder="templates"
)


@departamentos.route("/", methods=["GET"])
@login_required
def ver_departamentos():
    # departamentos = Departamento.query.all()
    
    page_default = 1
    por_pagina = 10
    pagina = request.args.get('pagina', page_default, type=int)
    departamentos = (
        Departamento.query #.order_by(Departamento.nombre.desc())
            .paginate(page=pagina, per_page=por_pagina)
    )

    return render_template(
        "departamentos/ver-departamentos.html", departamentos=departamentos
    )


# from sqlalchemy.orm import asdict
@departamentos.route("/departamento/<int:id>")
@login_required
def ver_departamento(id):
    departamento = Departamento.query.get_or_404(id)

    form = CrearDepartamento(
        nombre=departamento.nombre,
        ubicacion=departamento.ubicacion,
        nombre_coordinador=departamento.nombre_coordinador,
        linea_telefonica=departamento.linea_telefonica,
    )
    return render_template(
        "departamentos/ver-departamento.html", departamento=departamento, form=form
    )


@departamentos.route("/crear-departamento", methods=["GET", "POST"])
@login_required
def crear_departamento():
    if current_user.tipo != "admin":
        flash("Sólo un usuario administrador tiene permitido esa acción.", "success")
        return redirect(url_for("main.index"))
    # tipo-area
    # nombre-area
    # nombre-coor
    # torre
    # piso
    # ext-telefonica

    if request.method == "POST":
        # nombre = form.nombre.data #request.form['nombre']
        # ubicacion = form.ubicacion.data #request.form['ubicacion']
        # nombre_coordinador = form.nombre_coordinador.data #request.form['nombre_coordinador']
        # linea_telefonica = form.linea_telefonica.data #request.form['linea_telefonica']

        tipo_area = request.form["tipo-area"].strip().lower()
        nombre_area = request.form["nombre-area"].strip()
        nombre_coor = request.form["nombre-coor"].strip()
        linea_telefonica = request.form["ext-telefonica"].strip()
        torre = request.form["torre"].strip().lower()
        piso = request.form["piso"].strip()
        piso_texto = piso if piso != '0' else 'planta baja' 
        ubicacion = f"Torre {torre}, piso {piso_texto}, {tipo_area} {nombre_area}"

        departamento = Departamento(
            tipo=tipo_area,
            torre=torre,
            piso=piso,
            nombre=nombre_area,
            ubicacion=ubicacion,
            nombre_coordinador=nombre_coor,
            linea_telefonica=linea_telefonica,
        )
        db.session.add(departamento)
        db.session.commit()

        flash("El departamento ha sido registrado exitosamente!", "success")
        return redirect(url_for("departamentos.ver_departamentos"))

    elif request.method == "GET":
        return render_template("departamentos/crear-departamento.html")


@departamentos.route("/departamento/<int:id>/editar", methods=["GET", "POST"])
@login_required
def editar_departamento(id):
    if current_user.tipo != "admin":
        flash("Sólo un usuario administrador tiene permitido esa acción.", "success")
        return redirect(url_for("main.index"))
    
    departamento = Departamento.query.get_or_404(id)
    form = CrearDepartamento()

    if request.method == "POST":
        departamento.nombre = (form.nombre.data,)
        departamento.ubicacion = (form.ubicacion.data,)
        departamento.nombre_coordinador = (form.nombre_coordinador.data,)
        departamento.linea_telefonica = (form.linea_telefonica.data,)

        db.session.commit()

        flash(f"El departamento ID #{id} fue editado exitosamente!", "success")
        return redirect(url_for("departamentos.ver_departamentos"))

    elif request.method == "GET":
        form = CrearDepartamento(
            nombre=departamento.nombre,
            ubicacion=departamento.ubicacion,
            nombre_coordinador=departamento.nombre_coordinador,
            linea_telefonica=departamento.linea_telefonica,
        )
        return render_template(
            "departamentos/editar-departamento.html",
            departamento=departamento,
            form=form,
        )


@departamentos.route("/departamento/<int:id>/eliminar", methods=["GET", "POST"])
@login_required
def eliminar_departamento(id):
    if current_user.tipo != "admin":
        flash("Sólo un usuario administrador tiene permitido esa acción.", "success")
        return redirect(url_for("main.index"))
    
    if request.method == "POST":
        departamento = Departamento.query.get_or_404(id)

        # Eliminar el departamento s definir como nulo la propiedad de departamento_id de los reportes asociados
        # No funciona porque el departamento es un primary key en la tabla reportes
        # reportes_asociados = Reporte.query.filter_by(departamento_id=id).all()
        # for reporte in reportes_asociados:
        #     reporte.departamento_id = None

        db.session.delete(departamento)
        db.session.commit()

        flash(f"El departamento ID #{id} se elimino exitosamente!", "success")
        return redirect(url_for("departamentos.ver_departamentos"))

    elif request.method == "GET":
        abort(403)

@departamentos.route("/query", methods=["GET"])
# @departamentos.route("/query/<string:torre>/<string:piso>/<string:tipo>", methods=["GET"])
# def query(torre='none', piso='none', tipo='none'):
def query():
    # Request args method
    torre = request.args.get('torre')
    piso = request.args.get('piso')
    tipo = request.args.get('tipo')

    # Crear un objeto de consula, aplicar filtros condicionalmente, y ejecutar la consulta
    dep_query = Departamento.query # También válido
    # dep_query = db.session.query(Departamento)
    if torre != 'none':
        dep_query = dep_query.filter(Departamento.torre == torre)
    if piso != 'none':
        dep_query = dep_query.filter(Departamento.piso == piso)
    if tipo != 'none':
        dep_query = dep_query.filter(Departamento.tipo == tipo)
    
    # deps = dep_query.order_by(Departamento.tipo).all()
    deps = dep_query.all()
    
    return [dep.to_dict() for dep in deps]

src/routes/usuarios.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from src import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from src.utils.auth import login_manager
from src.models.usuario import Usuario
from src.models.reporte import Reporte
from src.models.notificacion import Notificacion
from src.models.comentario import Comentario
from src.forms.usuarios import (
    RegistroForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
    CambiarContraseñaForm,
)
from src.utils.usuarios import enviar_correo_recuperacion, notificar_cambio_contrasena

# from src.utils import save_picture, remove_picture, send_reset_email

usuarios = Blueprint("usuarios", __name__)


# Init login manager extension
# Cargar usuario en base al id de usuario de la sesión actual
# Devuelve el usuario correspondiente para ese id
@login_manager.user_loader
def load_user(user_id):
    return Usuario.query.get(int(user_id))


@usuarios.route("/ver-usuarios", methods=["GET"])
@login_required
def ver_usuarios():
    if current_user.tipo != "admin":
        return redirect(url_for("main.index"))

    query = Usuario.query
    
    page_default = 1
    por_pagina = 20
    pagina = request.args.get('pagina', page_default, type=int)

    usuarios = query.paginate(page=pagina, per_page=por_pagina)
    print(usuarios.first)
    # usuarios = Usuario.query.all()

    return render_template(
        "usuarios/ver-usuarios.html", usuarios=usuarios
    )

@usuarios.route("/registrar-usuario", methods=["GET", "POST"])
@login_required
def registrar_usuario():
    if current_user.tipo != "admin":
        return redirect(url_for("main.index"))

    form = RegistroForm()

    if request.method == 'POST' and form.validate():
        nombre_usuario = form.usuario.data.strip().lower()
        email = form.email.data.strip().lower()
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        tipo = request.form.get('tipo').strip()

        nuevo_usuario = Usuario(
            usuario=nombre_usuario,
            email=email,
            password=hashed_password,
            tipo=tipo,
        )
        
        db.session.add(nuevo_usuario)  # add query
        db.session.commit()  # commit changes

        flash("Tu cuenta ha sido creada exitosamente! Ahora puedes ingresar", "success")
        return redirect(url_for("usuarios.ver_usuarios"))
    return render_template("usuarios/registrar-usuario.html", title="Register", form=form)

# Ruta para eliminar reporte. Válida sólo para el método POST
@usuarios.route("/usuario/<int:id>/eliminar", methods=["POST"])
@login_required
def eliminar_usuario(id):
    usuario = Usuario.query.get_or_404(id)
    if current_user.tipo != 'admin' and current_user.id != usuario.id:
        abort(403)
        return

    if usuario.id == 1:
        # Acción prohibida: esta acción causaría daños permanentes al sistema y no se puede realizar.
        abort(403)
        return
    
    # Eliminar modelos relacionados si es necesario antes de eliminar el usuario
    # Obtener reportes del usuario
    reportes_usuario = Reporte.query.filter_by(usuario_id=usuario.id).all()
    for reporte in reportes_usuario:
        # Eliminar comentarios asociados a cada reporte
        comentarios = Comentario.query.filter_by(reporte_id=reporte.id).all()
        for comentario in comentarios:
            db.session.delete(comentario)
        db.session.delete(reporte)
    # Comentario.query.filter_by(usuario_id=usuario.id).delete()
    # Reporte.query.filter_by(usuario_id=usuario.id).delete()
    Notificacion.query.filter_by(usuario_id=usuario.id).delete()


    db.session.delete(usuario)
    db.session.commit()

    flash(f"El usuario ID #{id} se elimino exitosamente!", "success")
    return redirect(url_for("usuarios.ver_usuarios"))

@usuarios.route("/registrarse", methods=["GET", "POST"])
def registrarse():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = RegistroForm()
    print(form.email.label(text="Correo Electrónico"))
    if form.validate_on_submit():
        nombre_usuario = form.usuario.data.strip().lower()
        email = form.email.data.strip().lower()
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        
        nuevo_usuario = Usuario(
            usuario=nombre_usuario,
            email=email,
            password=hashed_password,
            tipo="solicitante"
        )
        
        db.session.add(nuevo_usuario)  # add query
        db.session.commit()  # commit changes

        flash("Tu cuenta ha sido creada exitosamente! Ahora puedes ingresar", "success")
        return redirect(url_for("usuarios.login"))
    return render_template("usuarios/registrarse.html", title="Register", form=form)


@usuarios.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = LoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        nombre_usuario = form.usuario.data.strip().lower()
        usuario = Usuario.query.filter_by(usuario=nombre_usuario).first()

        if not usuario:
            flash(
                "El nombre de usuario no está registrado. Verificalo o registrate",
                "danger"
            )

        elif usuario and bcrypt.check_password_hash(usuario.password, form.password.data):
            login_user(usuario, remember=form.remember.data)

            # Verificar si el usuario debe cambiar su contraseña
            if notificar_cambio_contrasena(current_user):
                return redirect(url_for('usuarios.cambiar_contrasena_primera_vez'))

            # If next arg from previous attempt to acces a route without logged in. Redirect to that attempted route
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.index"))

        else:
            flash(
                "No se ha podido ingresar. Por favor verifica el correo y la contraseña",
                "danger",
            )
    return render_template("usuarios/login.html", title="Login", form=form)


@usuarios.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("usuarios.login"))


@usuarios.route("/cuenta", methods=["GET", "POST"])
@login_required
def cuenta():
    form = UpdateAccountForm()
    # ON POST METHOD AS SUMBIT FORM
    if form.validate_on_submit():
        current_user.usuario = form.usuario.data.strip().lower()
        current_user.email = form.email.data.strip().lower()
        db.session.commit()

        flash("Tu cuenta ha sido actualizada exitosamente!", "success")
        return redirect(url_for("usuarios.cuenta"))
    # Populate form with current user email and username
    elif request.method == "GET":
        form.usuario.data = current_user.usuario
        form.email.data = current_user.email

    return render_template(
        "usuarios/cuenta.html", title="Account", form=form, usuario=current_user
    )  # , profile_img=profile_img


@usuarios.route("/cambiar-contrasena", methods=["GET", "POST"])
@login_required
def cambiar_contrasena():
    form = CambiarContraseñaForm()
    if form.validate_on_submit():
        if bcrypt.check_password_hash(current_user.password, form.password_actual.data):
            hashed_password = bcrypt.generate_password_hash(form.nueva_password.data).decode("utf-8")
            current_user.password = hashed_password
            db.session.commit()
            flash("Tu contraseña ha sido actualizada exitosamente!", "success")
            return redirect(url_for("usuarios.cuenta"))
        else:
            flash("La contraseña actual es incorrecta. Inténtalo de nuevo.", "danger")
    return render_template("usuarios/cambiar-contraseña.html", title="Cambiar contraseña", form=form)

# Ruta para cambiar la contraseña la primera vez que un usuario por defecto inicia sesión
@usuarios.route("/cambiar-contrasena-primera-vez", methods=["GET", "POST"])
@login_required
def cambiar_contrasena_primera_vez():
    form = CambiarContraseñaForm()
    if form.validate_on_submit():
        if bcrypt.check_password_hash(current_user.password, form.password_actual.data):
            hashed_password = bcrypt.generate_password_hash(form.nueva_password.data).decode("utf-8")
            current_user.password = hashed_password
            db.session.commit()
            flash("Tu contraseña ha sido actualizada exitosamente!", "success")
            return redirect(url_for("usuarios.cuenta"))
        else:
            flash("La contraseña actual es incorrecta. Inténtalo de nuevo.", "danger")
    return render_template("usuarios/cambiar-contraseña-primera-vez.html", form=form)

# PAGINATION PAGE FOR SPECIFIC USER POSTS
@usuarios.route("/user/<string:username>")
def user_posts(username):
    pass
    # page = request.args.get('page', 1, type=int)
    # user = Usuario.query.filter_by(username=username).first_or_404()
    # posts = Post.query.filter_by(author=user)\
    #     .order_by(Post.date_posted.desc())\
    #     .paginate(page=page, per_page=5)
    # return render_template('usuarios/user_posts.html', posts=posts, user=user)


@usuarios.route("/restablecer-contraseña", methods=['GET', 'POST'])
def restablecer_contrasena():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = Usuario.query.filter_by(email=form.email.data.strip().lower()).first()
        try:
            enviar_correo_recuperacion(user)
        except Exception as e:
            print(f"No se pudo enviar el correo de restablecimiento. Error: {e}")
            flash('Algo salió mal, el correo de restablecimiento no pudo ser enviado. Intenta más tarde', 'danger')

src/templates/usuarios/cambiar-contraseña-primera-vez.html
{% extends "layout-user-auth.html" %}

{% block title %}
- Ingresar
{% endblock %}

{% block content %}
<div class="container-fluid flex-grow-1 py-2">    
    <h2>Cambiar contraseña</h2>
    <p>Por razones de seguridad por favor cambia tu contraseña por una mas segura.</p>
    <form method="POST" action="{{ url_for('usuarios.cambiar_contrasena_primera_vez') }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.password_actual.label(class="form-label") }}
            {{ form.password_actual(class="form-control") }}
            {% for error in form.password_actual.errors %}
            <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.nueva_password.label(class="form-label") }}
            {{ form.nueva_password(class="form-control") }}
            {% for error in form.nueva_password.errors %}
            <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <div class="form-group">
            {{ form.confirmar_password.label(class="form-label") }}
            {{ form.confirmar_password(class="form-control") }}
            {% for error in form.confirmar_password.errors %}
            <div class="text-danger">{{ error }}</div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary mt-2">Cambiar contraseña</button>
    </form>

</div>
{% endblock %}

src/templates/usuarios/cuenta.html
{% extends 'layout.html' %}

{% block title %}
- Cuenta
{% endblock %}

{% block content %}
<div class="container-fluid flex-grow-1 py-2">
    <div class="row">
        {% include "messages.html" %}
    </div>

    <div class="row">
        <h2 class="account-heading">{{ usuario.usuario }}</h2>
        <!-- FORM HERE -->
        <!-- Empty action redirects to the same route -->
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="mb-2">Informacion de cuenta</legend>
                <div class="form-group">
                    {{ form.usuario.label(class="form-control-label") }}

                    {% if form.usuario.errors %}
                        {{ form.usuario(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.usuario.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.usuario(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    <!-- FIELD ERROR MESSAGES -->
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary mt-2") }}
            </div>
        </form>

        <a href="{{ url_for('usuarios.cambiar_contrasena')}}">Cambiar contraseña</a>
    </div>
</div>
{% endblock content %}

src/templates/usuarios/login.html
{% extends "layout-user-auth.html" %}

{% block title %}
- Ingresar
{% endblock %}

{% block content %}
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Iniciar sesión</legend>
            <div class="form-group mb-3">
                {{ form.usuario.label(class="form-label fw-bold") }}
                {% if form.usuario.errors %}
                    {{ form.usuario(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.usuario.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.usuario(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group mb-3">
                {{ form.password.label(class="form-label fw-bold") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check mb-3">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group mb-3">
            {{ form.submit(class="btn btn-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('usuarios.restablecer_contrasena') }}">¿Olvidaste tu contraseña?</a>
            </small>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            ¿No tienes una cuenta? <a class="ml-2" href="{{ url_for('usuarios.registrarse') }}">Regístrate</a>
        </small>
    </div>
{% endblock content %}

src/templates/usuarios/registrar-usuario.html
{% extends 'layout.html' %}

{% block title %}
- Registrar usuario
{% endblock %}


{% block content %}

<div class="container-fluid flex-grow-1 py-2">

    <form method="POST" action="{{ url_for('usuarios.registrar_usuario') }}">
        <h2>Nuevo usuario</h2>
        <!-- form.csrf_token Render CSRF token hidden field -->
        <!-- form.hidden_tag() Render fields of type hidden -->
        {{ form.hidden_tag() }}
        <ul class="list-unstyled row g-3">
            <li class="col-6">
                <!-- <label for="usuario" class="form-label fw-bold">Nombre de usuario:</label> -->
                {{ form.usuario.label(class="form-label fw-bold") }}
                {% if form.usuario.errors %}
                {{ form.usuario(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.usuario.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.usuario(class="form-control") }}
                {% endif %}
            </li>

            <li class="col-6">
                {{ form.email.label(class="form-label fw-bold") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control ") }}
                {% endif %}
            </li>
            <li class="col-6">
                {{ form.password.label(class="form-label fw-bold") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control ") }}
                {% endif %}
            </li>
            <li class="col-6">
                {{ form.confirm_password.label(class="form-label fw-bold") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control is-invalid") }}
                <div class="invalid-feedback">
                    <!-- VALIDATION FEEDBACK -->
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control ") }}
                {% endif %}
            </li>
            <li class="col-4">
                <label for="tipo" class="form-label fw-bold">Tipo:</label>
                <select name="tipo" id="torre" class="form-select col" required>
                    <option value="" selected>Selecciona el tipo de usuario</option>
                    <option value="admin">Administrador</option>
                    <option value="soporte">Soporte</option>
                    <option value="solicitante">Solicitante</option>
                </select>
            </li>

        </ul>
        <button type="submit" class="btn btn-primary w-100">Registrar usuario</button>
    </form>
</div>
{% endblock %}

src/templates/usuarios/ver-usuarios.html
{% extends 'layout.html' %}

{% block title %}
- Ver usuarios
{% endblock %}


{% block content %}
<div class="container-fluid flex-grow-1 py-2">
    <div class="row">
        {% include "messages.html" %}
    </div>
    
    <div class="row">
        <div class="col-auto">
            <h2>Usuarios</h2>
        </div>
        <div class="col-auto ms-auto">
            <button class="btn btn-primary">
                <a href="{{ url_for('usuarios.registrar_usuario') }}">Registrar usuario</a>
            </button>
        </div>
    </div>

    {% if usuarios.first %}

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nombre de usuario</td>
                <th scope="col">Correo</td>
                <th scope="col">Tipo</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            {% for usuario in usuarios %}
            <tr>
                <td>{{ usuario.usuario }}</td>
                <td>{{ usuario.email }}</td>
                <td>{{ usuario.tipo }}</td>

                <td>
                    <!-- 
                    <button class="btn btn-sm btn-outline-info">
                        <a href="{{ url_for('departamentos.ver_departamento', id=0) }}">Ver</a>
                    </button>
                    <button class="btn btn-sm btn-outline-secondary">
                        <a href="{{ url_for('departamentos.editar_departamento', id=0) }}">Editar</a>
                    </button>
                    -->
                    <button
                        class="btn btn-sm btn-outline-danger"
                        type="submit"
                        form="del-{{ usuario.id }}"
                        onclick="return confirm('¿Seguro que deseas eliminar el siguiente usuario: {{ usuario.usuario }}?')"
                        >Eliminar</button>
                </td>
                <form id="del-{{ usuario.id }}" action="{{ url_for('usuarios.eliminar_usuario', id=usuario.id) }}"
                    method="post">
                </form>
            </tr>
            {% endfor %}

        </tbody>
    </table>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% for nro_pag in usuarios.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
            {% if nro_pag %}
            {% if usuarios.page == nro_pag %}
            <li class="page-item active"><a class="page-link"
                    href="{{ url_for('usuarios.ver_usuarios', pagina=nro_pag) }}">{{ nro_pag }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link"
                    href="{{ url_for('usuarios.ver_usuarios', pagina=nro_pag) }}">{{ nro_pag }}</a></li>
            {% endif %}
            {% else %}
            <li class="page-item"><a href="#" class="page-link">...</a></li>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>

    {% else %}
    <p>No hay usuarios para mostrar</p>
    {% endif %}

</div>
{% endblock %}