src/models/departamento.py
from src.utils.db import db

class Departamento(db.Model):
    __tablename__ = "departamentos"

    id = db.Column(db.Integer, primary_key=True)
    torre = db.Column(db.String(2), nullable=False)
    piso = db.Column(db.String(2), nullable=False)
    tipo = db.Column(db.String(20), nullable=False)
    nombre = db.Column(db.String(50), nullable=False)
    ubicacion = db.Column(db.String(200), nullable=False)
    nombre_coordinador = db.Column(db.String(100)) #, nullable=False)
    linea_telefonica = db.Column(db.String(20))


    def __repr__(self):
        return f"Departamento('{self.nombre}')"

    def get_piso_texto(self):
        return self.piso if self.piso != '0' else 'planta baja'

src/forms/departamentos.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, HiddenField
from wtforms.validators import DataRequired

class CrearDepartamento(FlaskForm):
    nombre = StringField('Nombre:', validators=[DataRequired()])
    ubicacion = StringField('Ubicacion:', validators=[DataRequired()])
    nombre_coordinador = StringField('Coordinador:')
    linea_telefonica = StringField('Linea telefonica:')
    
    # estado = SelectField('Estado', choices=[('cpp', 'C++'), ('py', 'Python'), ('text', 'Plain Text')])

    submit = SubmitField('Registrar')

src/routes/departamentos.py
from flask import Blueprint, flash, render_template, request, redirect, url_for, abort
from flask_login import current_user, login_required
from src.models.departamento import Departamento
from src.models.reporte import Reporte
from src.forms.departamentos import CrearDepartamento
from src.utils.departamentos import AREAS_TIPOS
from src import db
from sqlalchemy.sql import func

departamentos = Blueprint(
    "departamentos", __name__, url_prefix="/departamentos", template_folder="templates"
)


@departamentos.route("/", methods=["GET"])
@login_required
def ver_departamentos():
    # departamentos = Departamento.query.all()
    
    page_default = 1
    por_pagina = 10
    pagina = request.args.get('pagina', page_default, type=int)
    departamentos = (
        Departamento.query #.order_by(Departamento.nombre.desc())
            .paginate(page=pagina, per_page=por_pagina)
    )

    return render_template(
        "departamentos/ver-departamentos.html", departamentos=departamentos
    )


# from sqlalchemy.orm import asdict
@departamentos.route("/departamento/<int:id>")
@login_required
def ver_departamento(id):
    departamento = Departamento.query.get_or_404(id)

    form = CrearDepartamento(
        nombre=departamento.nombre,
        ubicacion=departamento.ubicacion,
        nombre_coordinador=departamento.nombre_coordinador,
        linea_telefonica=departamento.linea_telefonica,
    )
    return render_template(
        "departamentos/ver-departamento.html", departamento=departamento, form=form
    )


@departamentos.route("/crear-departamento", methods=["GET", "POST"])
@login_required
def crear_departamento():
    if current_user.tipo != "admin":
        flash("Sólo un usuario administrador tiene permitido esa acción.", "success")
        return redirect(url_for("main.index"))
    # tipo-area
    # nombre-area
    # nombre-coor
    # torre
    # piso
    # ext-telefonica

    if request.method == "POST":
        # nombre = form.nombre.data #request.form['nombre']
        # ubicacion = form.ubicacion.data #request.form['ubicacion']
        # nombre_coordinador = form.nombre_coordinador.data #request.form['nombre_coordinador']
        # linea_telefonica = form.linea_telefonica.data #request.form['linea_telefonica']

        tipo_area = request.form["tipo-area"].strip().lower()
        nombre_area = request.form["nombre-area"].strip()
        nombre_coor = request.form["nombre-coor"].strip()
        linea_telefonica = request.form["ext-telefonica"].strip()
        torre = request.form["torre"].strip().lower()
        piso = request.form["piso"].strip()
        piso_texto = piso if piso != '0' else 'planta baja' 
        ubicacion = f"Torre {torre}, piso {piso_texto}, {tipo_area} {nombre_area}"

        departamento = Departamento(
            tipo=tipo_area,
            torre=torre,
            piso=piso,
            nombre=nombre_area,
            ubicacion=ubicacion,
            nombre_coordinador=nombre_coor,
            linea_telefonica=linea_telefonica,
        )
        db.session.add(departamento)
        db.session.commit()

        flash("El departamento ha sido registrado exitosamente!", "success")
        return redirect(url_for("departamentos.ver_departamentos"))

    elif request.method == "GET":
        return render_template("departamentos/crear-departamento.html")


@departamentos.route("/departamento/<int:id>/editar", methods=["GET", "POST"])
@login_required
def editar_departamento(id):
    if current_user.tipo != "admin":
        flash("Sólo un usuario administrador tiene permitido esa acción.", "success")
        return redirect(url_for("main.index"))
    
    departamento = Departamento.query.get_or_404(id)
    form = CrearDepartamento()

    if request.method == "POST":
        departamento.nombre = (form.nombre.data,)
        departamento.ubicacion = (form.ubicacion.data,)
        departamento.nombre_coordinador = (form.nombre_coordinador.data,)
        departamento.linea_telefonica = (form.linea_telefonica.data,)

        db.session.commit()

        flash(f"El departamento ID #{id} fue editado exitosamente!", "success")
        return redirect(url_for("departamentos.ver_departamentos"))

    elif request.method == "GET":
        form = CrearDepartamento(
            nombre=departamento.nombre,
            ubicacion=departamento.ubicacion,
            nombre_coordinador=departamento.nombre_coordinador,
            linea_telefonica=departamento.linea_telefonica,
        )
        return render_template(
            "departamentos/editar-departamento.html",
            departamento=departamento,
            form=form,
        )


@departamentos.route("/departamento/<int:id>/eliminar", methods=["GET", "POST"])
@login_required
def eliminar_departamento(id):
    if current_user.tipo != "admin":
        flash("Sólo un usuario administrador tiene permitido esa acción.", "success")
        return redirect(url_for("main.index"))
    
    if request.method == "POST":
        departamento = Departamento.query.get_or_404(id)

        # Eliminar el departamento s definir como nulo la propiedad de departamento_id de los reportes asociados
        # No funciona porque el departamento es un primary key en la tabla reportes
        # reportes_asociados = Reporte.query.filter_by(departamento_id=id).all()
        # for reporte in reportes_asociados:
        #     reporte.departamento_id = None

        db.session.delete(departamento)
        db.session.commit()

        flash(f"El departamento ID #{id} se elimino exitosamente!", "success")
        return redirect(url_for("departamentos.ver_departamentos"))

    elif request.method == "GET":
        abort(403)

@departamentos.route("/query", methods=["GET"])
# @departamentos.route("/query/<string:torre>/<string:piso>/<string:tipo>", methods=["GET"])
# def query(torre='none', piso='none', tipo='none'):
def query():
    # Request args method
    torre = request.args.get('torre')
    piso = request.args.get('piso')
    tipo = request.args.get('tipo')

    # Crear un objeto de consula, aplicar filtros condicionalmente, y ejecutar la consulta
    dep_query = Departamento.query # También válido
    # dep_query = db.session.query(Departamento)
    if torre != 'none':
        dep_query = dep_query.filter(Departamento.torre == torre)
    if piso != 'none':
        dep_query = dep_query.filter(Departamento.piso == piso)
    if tipo != 'none':
        dep_query = dep_query.filter(Departamento.tipo == tipo)
    
    # deps = dep_query.order_by(Departamento.tipo).all()
    deps = dep_query.all()
    
    return [dep.to_dict() for dep in deps]

src/templates/departamentos/crear-departamento.html
{% extends 'layout.html' %}

{% block title %}
- Registrar departamento
{% endblock %}


{% block content %}

<div class="container-fluid flex-grow-1 py-2">
    <div class="row">
        {% include "messages.html" %}
    </div>
    
    <div class="row">
        <form action="{{ url_for('departamentos.crear_departamento') }}" method="post">
            <h2>Nueva área</h2>
            <fieldset>
                <!-- <legend>Ubicación</legend> -->
                <ul class="list-unstyled row g-3">
                    <li class="col-4">
                        <label for="tipo-area" class="form-label"><strong>Tipo de área:</strong></label>
                        <select name="tipo-area" id="tipo-area" class="form-select">
                            <option value="" selected>Selecciona un tipo de área</option>
                            <option value="aula">Aula</option>
                            <option value="coordinación">Coordinación</option>
                            <option value="cubiculo">Cubiculo</option>
                            <option value="dirección">Dirección</option>
                            <option value="departamento">Departamento</option>
                            <option value="dependencia">Dependencia</option>
                            <option value="laboratorio">Laboratorio</option>
                            <option value="unidad">Unidad</option>
                            <option value="oficina">Oficina</option>
                        </select>
        
                    </li>
                    <li class="col-8">
                        <label for="nombre-area" class="form-label"><strong>Nombre del área:</strong></label>
                        <input type="text" name="nombre-area" id="nombre-area" class="form-control" placeholder="Servicios generales">
                    </li>
                    <li class="col-12">
                        <label for="nombre-coor" class="form-label"><strong>Nombre del coordinador:</strong></label>
                        <input type="text" name="nombre-coor" id="nombre-coor" class="form-control" placeholder="José Morales">
                        <div class="form-text">Ingresa el nombre del coordinador o persona encargada del área</div>
                    </li>
                    <li class="col-4">
                        <label for="torre" class="col-auto form-label m-0"><strong>Torre:</strong></label>
                        <select name="torre" id="torre" class="col form-select">
                            <option value="" selected>Seleccionar torre</option>
                            <option value="a">A</option>
                            <option value="b">B</option>
                            <option value="c">C</option>
                            <option value="d">D</option>
                            <option value="e">E</option>
                            <option value="f">F</option>
                        </select>
                    </li>
                    <li class="col-4">
                        <label for="piso" class="col-auto form-label m-0"><strong>Piso:</strong></label>
                        <select name="piso" id="piso" class="col form-select">
                            <option value="" selected>Seleccionar piso</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="0">Planta baja</option>
                        </select>
                    </li>
                    <li class="col-4">
                        <label for="ext-telefonica" class="col-auto form-label m-0"><strong>Ext. telefónica:</strong></label>
                        <input type="text" name="ext-telefonica" id="ext-telefonica" class="col form-control" placeholder="3311">
                    </li>
                </ul>
            </fieldset>
            <!-- <input type="hidden" name="csrf_token" value="{ csrf_token() }"> -->
            <button type="submit" class="btn btn-primary w-100">Registrar área</button>
        </form>
    </div>
</div>
{% endblock %}

src/templates/departamentos/editar-departamento.html
{% extends 'layout.html' %}

{% block title %}
- Editar departamento
{% endblock %}


{% block content %}

<div class="container-fluid flex-grow-1 py-2">
    <div class="row">
        {% include "messages.html" %}
    </div>
    <div class="row">
        <h2>Editar departamento</h2>
        <form action="{{ url_for('departamentos.editar_departamento', id=departamento.id) }}" method="post">
            <ul>
                <li>
                    {{ form.nombre.label }}
                    {{ form.nombre }}
                    <!-- form.titulo(disabled='True') -->
                </li>
                <li>
                    {{ form.ubicacion.label }}
                    {{ form.ubicacion }}
                </li>
                <li>
                    <!-- Cambiar por un input check -->
                    {{ form.nombre_coordinador.label }}
                    {{ form.nombre_coordinador }}
                </li>
                <li>
                    {{ form.linea_telefonica.label }}
                    {{ form.linea_telefonica }}
                </li>
                <li>
                    {{ form.submit }}
                </li>
            </ul>
        </form>
    </div>
</div>

{% endblock %}

src/templates/departamentos/ver-departamento.html
{% extends 'layout.html' %}

{% block title %}
 - Departamento: {{ departamento.nombre | capitalize() }}
{% endblock %}


{% block content %}
<div class="container-fluid flex-grow-1 py-2">
  <div class="row">
      {% include "messages.html" %}
  </div>
  <div class="row">
    <h2>{{ departamento.nombre | upper() }}</h2>
    <ul>
      <li>Nombre: {{ departamento.nombre | capitalize() }}</li>
      <li>Ubicacion: {{ departamento.ubicacion | capitalize() }}</li>
      <li>Nombre_coordinador: {{ departamento.nombre_coordinador | capitalize() }}</li>
      <li>Linea telefonica: {{ departamento.linea_telefonica | capitalize() }}</li>
    </ul>
  </div>

</div>

{% endblock %}

src/templates/departamentos/ver-departamentos.html
{% extends 'layout.html' %}

{% block title %}
- Ver departamentos
{% endblock %}


{% block content %}
<div class="container-fluid flex-grow-1 py-2">
    <div class="row">
        {% include "messages.html" %}
    </div>
    
    <div class="row align-items-center">
        <div class="col-auto d-flex align-items-baseline">
            <h2>Departamentos</h2>
            <div class="ms-1">{{departamentos.first}}-{{departamentos.last}} / {{departamentos.total}}</div>
        </div>
        <div class="col-auto ms-auto">
            <button class="btn btn-primary">
                <a href="{{ url_for('departamentos.crear_departamento') }}">Registrar departamento</a>
            </button>
        </div>
    </div>

    {% if departamentos.first %}
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nombre</td>
                <th scope="col">Ubicacion</td>
                <th scope="col">Nombre coordinador</td>
                <th scope="col">Linea telefonica</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            {% for departamento in departamentos.items %}
            <tr>
                <td>{{ departamento.nombre }}</td>
                <td>{{ departamento.ubicacion }}</td>
                <td>{% if departamento.nombre_coordinador %} {{ departamento.nombre_coordinador }} {% endif %}</td>
                <td>{% if departamento.linea_telefonica %} {{ departamento.linea_telefonica }} {% endif %}</td>

                <td>
                    <button class="btn btn-sm btn-outline-info">
                        <a href="{{ url_for('departamentos.ver_departamento', id=departamento.id) }}">Ver</a>
                    </button>
                    <!--
                    <button class="btn btn-sm btn-outline-secondary">
                        <a href="{{ url_for('departamentos.editar_departamento', id=departamento.id) }}">Editar</a>
                    </button>
                    <button
                        class="btn btn-sm btn-outline-danger"
                        type="submit"
                        form="del-{{departamento.id}}"
                        onclick="return confirm('¿Seguro que deseas eliminar el siguiente demartamento: {{ departamento.nombre }}?')"
                        >Eliminar</button>
                    -->
                </td>
                <!-- 
                    <form id="del-{{ departamento.id }}"
                    action="{{ url_for('departamentos.eliminar_departamento', id=departamento.id) }}" method="post">
                -->
                </form>
            </tr>
            {% endfor %}

        </tbody>
    </table>

    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% for nro_pag in departamentos.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
            {% if nro_pag %}
            {% if departamentos.page == nro_pag %}
            <li class="page-item active"><a class="page-link"
                    href="{{ url_for('departamentos.ver_departamentos', pagina=nro_pag) }}">{{ nro_pag }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link"
                    href="{{ url_for('departamentos.ver_departamentos', pagina=nro_pag) }}">{{ nro_pag }}</a></li>
            {% endif %}
            {% else %}
            <li class="page-item"><a href="#" class="page-link">...</a></li>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>

    <!-- <label for="por-pag-sel">Por pág.:</label>
    <select class="form-select form-select-sm" id="por-pag-sel" aria-label="Small select example">
        <option value="10">10</option>
        <option value="25">25</option>
        <option value="50">50</option>
    </select> -->
    {% else %}
    <p>No hay departamentos para mostrar</p>
    {% endif %}
</div>
{% endblock %}